### ISSUE TITLE
在低配主机(1c2g)上CPU满载是正常的吗

### ISSUE THREAD

**Issue by lonelyion** [K-bai/meumy-live-showcase#4]
![image](https://user-images.githubusercontent.com/25267689/200514206-f201e8e0-2934-4c90-a432-34a2cee2f130.png)

**Comment by K-bai** [comment]
正常的，调用了分词会比较消耗cpu
但不会持续太长时间 如果主机上还有其他服务可以考虑用运维工具限制cpu使用量
